[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "sketch wheel slow example provide obscure food column level custom twist hard motion purchase one render cup cherry kangaroo south black senior when custom"
